name: LEIHS/v5/integration
windows:
  2:
    name: apache2
    command: |
      kill -INT $(lsof -t -wni tcp:3200)
      while true; do
        rm -rf logs/*
        DYLD_LIBRARY_PATH=/opt/local/lib/apache2/modules/  \
          /opt/local/sbin/httpd -d reverse-proxy -f conf/httpd.conf -e info -DFOREGROUND
        sleep 1
      done
  7: 
    name: tests
