name: LEIHS/leihs/integration
windows:
  2:
    name: reverse-proxy
    command: |
      ./bin/docker-run
  7:
    name: tests
    command: |
      export TEST_AUTH_SYSTEM_PORT=3245
      export LEIHS_MAIL_SMTP_PORT=32025
      export LEIHS_MAIL_POP3_PORT=32110
      export NOPRY_ON_EXCEPTION=YES
