jobs:
   integration-tests:
    name: Integration Tests

    # TEMP
    priority: 1337

    task_defaults:
      traits:
        # TEMP
        ci-g2016-01: yes
        vagrant: yes
        virtualbox: yes

    run_when: &DEFAULT_TRIGGERS
      any branch matches:
        type: branch
        include_match: ^.+$

    context:
      include:
        - path: cider-ci/integration-tests.yml
